// 로그 접힘 검수 — 판을 돌려 소환이 반복될 때 「×n」 으로 접히는지 본다.
const CDP="http://127.0.0.1:9333", URL="http://127.0.0.1:8774/index.html";
const ver=await (await fetch(CDP+"/json/version")).json();
const bws=new WebSocket(ver.webSocketDebuggerUrl); let id=0; const pend=new Map();
const raw=(m,p={},s)=>{const i=++id;bws.send(JSON.stringify({id:i,method:m,params:p,sessionId:s}));return new Promise((res,rej)=>pend.set(i,{res,rej}));};
bws.addEventListener("message",ev=>{const m=JSON.parse(ev.data);if(m.id&&pend.has(m.id)){const p=pend.get(m.id);pend.delete(m.id);return m.error?p.rej(new Error(JSON.stringify(m.error))):p.res(m.result);}});
await new Promise(r=>bws.addEventListener("open",r));
const {targetId}=await raw("Target.createTarget",{url:URL});
const {sessionId}=await raw("Target.attachToTarget",{targetId,flatten:true});
const S=(m,p)=>raw(m,p,sessionId);
await S("Page.enable");await S("Runtime.enable");
await S("Emulation.setDeviceMetricsOverride",{width:1512,height:863,deviceScaleFactor:2,mobile:false});
await S("Page.reload",{ignoreCache:true});
await new Promise(r=>setTimeout(r,3500));
const ev=async(fn)=>{const r=await S("Runtime.evaluate",{expression:fn,awaitPromise:true,returnByValue:true});return r.result.value;};
await ev(`window.__toDungeon(); true`);
await new Promise(r=>setTimeout(r,12000));
const out=await ev(`JSON.stringify({log: window.__S.log, dupPairs: (()=>{const t=window.__S.log.map(l=>l.replace(/ <b[^>]*>×\\d+<\\/b>$/,""));let d=0;for(let i=1;i<t.length;i++) if(t[i]===t[i-1]) d++;return d;})()})`);
console.log(out);
await raw("Target.closeTarget",{targetId});
process.exit(0);
