/* V-118 — **같은 사람 · 같은 순간에 문만 여닫아** 옛 딱지와 지금 딱지를 위아래로 붙인다. */
const CDP="http://127.0.0.1:9333",URL="http://127.0.0.1:8774/index.html";
import fs from "node:fs";
const ver=await (await fetch(CDP+"/json/version")).json();
const bws=new WebSocket(ver.webSocketDebuggerUrl);let id=0;const pend=new Map();
const raw=(m,p={},s)=>{const i=++id;bws.send(JSON.stringify({id:i,method:m,params:p,sessionId:s}));return new Promise((res,rej)=>pend.set(i,{res,rej}))};
bws.addEventListener("message",e=>{const m=JSON.parse(e.data);if(m.id&&pend.has(m.id)){const p=pend.get(m.id);pend.delete(m.id);return m.error?p.rej(new Error(JSON.stringify(m.error))):p.res(m.result)}});
await new Promise(r=>bws.addEventListener("open",r));
const {targetId}=await raw("Target.createTarget",{url:URL});
const {sessionId}=await raw("Target.attachToTarget",{targetId,flatten:true});
const S=(m,p)=>raw(m,p,sessionId);await S("Page.enable");await S("Runtime.enable");
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const ev=async e=>(await S("Runtime.evaluate",{expression:e,returnByValue:true,awaitPromise:true})).result?.value;
const SEED=`(()=>{const C=globalThis.__C,M=C.META;M.lv=46;M.gold=1823400;M.deepest=34;
 M.plus={wand:19,robe:19,charm:19,helm:19,glove:19,ring:19};
 const ks=["wand","robe","charm","helm","glove","ring"];
 ks.forEach((k,i)=>{M.equip[k]=C.mkItem(k,(C.GEAR[k].tiers.length-1)-(i%2),false,30)});
 C.saveMeta();return 1})()`;
await S("Emulation.setDeviceMetricsOverride",{width:1512,height:863,deviceScaleFactor:2,mobile:false});
await S("Page.reload",{ignoreCache:true});await wait(1200);
await ev(`(()=>{try{localStorage.clear()}catch(e){}return 1})()`);
await S("Page.reload",{ignoreCache:true});await wait(2300);
await ev(`(async()=>{globalThis.__C=await import('./js/core.js');return 1})()`);
await ev(SEED);
await S("Page.reload",{ignoreCache:true});await wait(2500);
await ev(`(()=>{const b=[...document.querySelectorAll('button,.beltBtn,[data-win]')].find(x=>/능력치/.test(x.textContent));if(b)b.click();return 1})()`);
await wait(900);
/* 투구·부적·장갑이 다 드는 자리 */
const box = await ev(`(()=>{const es=[...document.querySelectorAll('.pdSlot')].filter(e=>e.getBoundingClientRect().width>0);
 let x0=1e9,y0=1e9,x1=-1e9,y1=-1e9; es.forEach(e=>{const r=e.getBoundingClientRect();
  x0=Math.min(x0,r.left);y0=Math.min(y0,r.top);x1=Math.max(x1,r.right);y1=Math.max(y1,r.bottom)});
 return {x:Math.floor(x0)-8,y:Math.floor(y0)-8,width:Math.ceil(x1-x0)+16,height:Math.ceil(y1-y0)+16}})()`);
const shot=async n=>{const {data}=await S("Page.captureScreenshot",{format:"png",clip:{...box,scale:2}});
  fs.writeFileSync("tmp/v118_cmp_"+n+".png",Buffer.from(data,"base64"));};
await ev(`document.body.classList.add("plusold")`);await wait(320);await shot("old");
await ev(`document.body.classList.remove("plusold")`);await wait(320);await shot("new");
console.log("찍음", JSON.stringify(box));
await raw("Target.closeTarget",{targetId});process.exit(0);
